# Generated by Django 3.2.19 on 2023-06-13 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='0 штук не может быть'), django.core.validators.RegexValidator(message='Пожалуйста, введите число.', regex='^\\d+$')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.Amount', to='recipe.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
